### ISSUE TITLE
libp2p logo refresh

### ISSUE THREAD

**Issue by jesseclay** [libp2p/libp2p#12]
Hey All!

We're (Protocol Labs) planning to refresh the libp2p website, and with that it makes a lot of sense that we have a logo to go along with it!

Would love any & all feedback on this process. 

We're trying to find a logo that symbolizes the core of libp2p: peers forging connections with each other over a variety of protocols; finding content & transferring it.

So far we've come up with these rough ideas, the lines here could be interpreted as separate peers. This is all still preliminary so nothing set in stone (though we are moving fast to quickly settle on something). 

Any thoughts or ideas throw them out there!
![libp2p_designsheet2](https://cloud.githubusercontent.com/assets/1719763/22353436/69bb2b68-e3ee-11e6-91ce-13a7a31c7e86.jpg)
![libp2p_designsheet1](https://cloud.githubusercontent.com/assets/1719763/22353449/7f554eae-e3ee-11e6-8cd4-5ec8c797996c.jpg)

**Comment by jesseclay** [comment]
Here's another proposal I'm leaning more towards

[libp2p_logo_small.pdf](https://github.com/libp2p/libp2p/files/743747/libp2p_logo_small.pdf)


@diasdavid @VictorBjelkholm

**Comment by daviddias** [comment]
oh, that is awesome! I really like it @jesseclay :D 

just not a fan of the double shadow on some of the boxes

![image](https://cloud.githubusercontent.com/assets/1211152/22503619/7b9c23a2-e86a-11e6-8694-31077cbe9eca.png)

gives the idea they are hollow

**Comment by jesseclay** [comment]
Yeah left that in the feedback. Let's see what we get next!

**Comment by jesseclay** [comment]
I'm delighted to declare we've finally settled on a logo! Next step, which of these do you think looks best?


![](https://cloud.githubusercontent.com/assets/22168118/22774370/0ee0185c-eea7-11e6-9bfa-f220ae3ac2ad.png)

**Comment by jesseclay** [comment]
@diasdavid @VictorBjelkholm @jbenet @dignifiedquire @Kubuxu @whyrusleeping ^^^

**Comment by dignifiedquire** [comment]
Sweet :) I think the bottom middle and bottom right look the best. They gray just doesn't match as well to the colorful logo

**Comment by ghost** [comment]
> Sweet :) I think the bottom middle and bottom right look the best. They gray just doesn't match as well to the colorful logo

Agreed

**Comment by daviddias** [comment]
I like all of them, can't we use all of them?

**Comment by jesseclay** [comment]
@diasdavid 

we can do

**Comment by jbenet** [comment]
- I would suggest not misaligning the cube **(2, 5)**. this logo is going to go into lots of hex grids -- the cube misaligned will look pretty dumb.
- People brought up: making sure the text "libp2p" is printed, as otherwise the cubes are not clear. **(agree)**
  - Consider doing what the IPFS logo does: "IPFS" written on top. (this may work on this one. maybe not).
  - Consider using the text on the side **(4)**
- I think ultimately, we won't really know until we print a few as stickers and try them out in the real environment.
- Note: when showing a list of logos, please add numbers (or letters) to easily refer to them.

### misaligned cube example

![image](https://cloud.githubusercontent.com/assets/138401/22882392/c1ab7b70-f19f-11e6-93f3-d48f9672b551.png)

### numbered logos

![image](https://cloud.githubusercontent.com/assets/138401/22882461/0057296e-f1a0-11e6-8e03-4fd19eb890da.png)

**Comment by jesseclay** [comment]
@jbenet seems to me that if you don't want to "misalign" the cube then you need to make libp2p way smaller (probably small enough that you mind as well remove it altogether) or move it to the side, as is done in #4. 

For the moment I still think #5 is best.

**Comment by daviddias** [comment]
WE HAVE A LOGO :D
