### ISSUE TITLE
simple-rpc

### ISSUE THREAD

**Issue by daviddias** [libp2p/libp2p#23]
> This is my first draft notes. I want to expand on these more

Following https://github.com/libp2p/interop/issues/1, we need an RPC library that:

- Has documentation generation support
- Has tests generation support
- Has client generation support
- Can be mounted over any Duplex Stream so that it fits right on top libp2p stream (e.g https://www.npmjs.com/package/znode)

Ideally, it would also:

- Use IPLD nodes as the transfer objects so that we don't have to stick to one serialization format (i.e dag-cbor, raw, etc)
- Have support for streaming files and directories (like tar-stream) built-in

Lot's of learn from:

- json-rpc http://www.jsonrpc.org, spec, learnings, tooling and more

**Comment by Kubuxu** [comment]
I am very intrigued and amazed by (capnproto)[https://capnproto.org/rpc.html] and its RPC model. It is extremely powerful but might not be the best fit for network RPC (I am not sure).

**Comment by ghost** [comment]
> - Can be mounted over any Duplex Stream so that it fits right on top libp2p stream (e.g https://www.npmjs.com/package/znode)
> - Use IPLD nodes as the transfer objects so that we don't have to stick to one serialization format (i.e dag-cbor, raw, etc)
> - Have support for streaming files and directories (like tar-stream) built-in

Hold on, I feel like these requirements are a step ahead. Let's figure out what the API should do before setting requirements for an RPC library. Otherwise a premature library choice will likely bias our API design.

(File and directory transfer!?!? :D Agreed on the requirements that I didn't quote, though.)

**Comment by warpfork** [comment]
gRPC does a lot of interesting things.  The ability to get multiple typed object streams, single or bi directional, multiplexed over the connection is pretty nice.

AFAIK, it's pretty emphatic about protobufs, and last time I checked it also requires a fairly remarkable amount of code to actually plug in variable low level transports, neither of which make it easy to integrate with if you aren't 10000% on board the google train.  But some concepts may still be good food for thought.

**Comment by hsanjuan** [comment]
Regarding: https://godoc.org/github.com/hsanjuan/go-libp2p-gorpc

The actual protocol is:

* Client open streams with RPC-protocol-ID
* Sends:
```
{
    "Name": "Objectname",
    "Method": "Objectmethod"
}
``` 
* Sends the arguments (it can be whatever)
* Server parses, casts, finds the right Object/Method and calls it
* Server sends the results
* Client reads Response Header:
```
{
  "ServiceID": { "Name": "ObjectName", "Method": "method" },
   "Error": "msg", 
   "ErrType": 0
}
```
* Reads response body (it can be whatever)
* Close

The fact that there are limitations on how the RPC methods look (`func A(in, *out) error`) is because we need to be able to `reflect` and cast things correctly in order to make calls. The more flexibility you add here, the more reflection code you need, the more likely you are to hit panics or worse. In other languages it is way more natural to call stuff with whatever, but not in `Go`.

I think that if you need something as versatile as gRPC, we should use gRPC, with a libp2p transport and not re-invent the wheel. If we want something really simple like go-libp2p-gorpc, we should probably have a stricter set of rules on how the methods and arguments look, and the feature set, making language-specific implementations super easy and short.

**Comment by mikeal** [comment]
Just got linked to this issue by @daviddias :)

I wrote znode and can speak a little to what made it so "simple."

* Service discovery is immediate and automatic. This has the added benefit of being done on the first roundtrip and is part of any other negotiation that needs to take place. The internals of service discovery are re-used for dynamic method creation.
* Using `msgpack`, which for these purposes is just JSON + binary, was important because alternatives like protobuf are strongly typed which means all the interfaces anyone creates will end up having to be strongly typed.
* Keep RPC calls atomic: Don't support streams in RPC. 
  * Streams are a layer above RPC. If you need a stream of data you can use the RPC system to signal the information to negotiate a substream at a layer above if you want (I've done this before in a swarm library).
  * If you want one node to start sending multiple blocks to another node you can just instrument that as series of RPC calls in the other direction since the channel is bi-directional.
    * Node-A calls `sendAll(identifier, function write {})` on Node-B. Node-B replies with a cancel method.
    * Node-B calls Node-A's write(Block) for every block.
    * Node-B calls write(null) when finished.
    * Note that blocks are not necessarily written in order, which means the node can parallelize the lookups from its own Block store as it sees fit.

Everything else is just API sugar and a lot of management of in-flight requests to promises on each end.

**Comment by magik6k** [comment]
There is https://github.com/libp2p/go-libp2p-daemon which seems related and uses protobuf messages, cc @vyzo

**Comment by raulk** [comment]
Can we think about this like a peer-to-peer equivalent of the [Istio service mesh](https://istio.io/)?

**Comment by daviddias** [comment]
Received this today, found it super interesting and relevant to this thread

[`eRPC (efficient RPC) is a new general-purpose remote procedure call (RPC) library that offers performance comparable to specialized systems`](https://blog.acolyer.org/2019/03/18/datacenter-rpcs-can-be-general-and-fast/)

> **eRPC just needs good old UDP**

**Comment by shanejonas** [comment]
JSON-RPC 2.0 and OpenRPC tooling for documentation generation: https://open-rpc.org

tooling and code generation support here: https://github.com/open-rpc

JSON-RPC 2.0 is just a very simple protocol, can be used anywhere, over any transport.

**Comment by daviddias** [comment]
@shanejonas super interesting! thank you so much for sharing the update about OpenRPC, need to play with it soon!
