### ISSUE TITLE
Adding some missing functionality to JS libp2p libraries

### ISSUE THREAD

**Issue by Mikerah** [libp2p/libp2p#64]
Hi from the ChainSafe team!

This year, we have started implementing [gossipsub in JS](https://github.com/ChainSafeSystems/gossipsub-js/tree/gossip_implementation). The gossipsub specification isn't enough (maybe, I'm too spoilt by the ETH2.0 specs) to start implementing from scratch. As such, we are going off the Go implementation of the protocol. 

While going through the Go implementation and trying to make sure we stick as much as we can to its functionality in JS, we realized that there is quite of bit of disparity between some of the same Go and JS modules. 

We are planning on adding the needed functionality before we continue on with our Gossipsub implementation.

Were there any plans to do so for this year from the libp2p team? We are definitely interested in collaborating.

**Comment by raulk** [comment]
Totally! As a first stab, it would be great to collaborate to identify/solve those areas of disparity. I know @jacobheun and @vasco-santos already keep an account in their heads, but it might be worth working together on an enumeration to gain alignment. Some things might be different by design, while others will definitely need levelling up.

@Mikerah, do you guys already have a list of what you’ve identified on your end?

**Comment by Mikerah** [comment]
I have started a separate [issue](https://github.com/ChainSafeSystems/gossipsub-js/issues/11) in our gossipsub repo. It's a start but I will be more specific as I start identifying the exact changes.
