### ISSUE TITLE
add discuss.libp2p.io badges to all repos

### ISSUE THREAD

**Issue by raulk** [libp2p/libp2p#74]
Here's the badge we can use:

![Discourse posts](https://img.shields.io/discourse/https/discuss.libp2p.io/posts.svg)

**Comment by vasco-santos** [comment]
@raulk is the plan to put that badge in all `libp2p` repos?

**Comment by raulk** [comment]
@vasco-santos That's what I suggest. No PR needed, just an automated commit on master.

**Comment by vasco-santos** [comment]
Yeah, cool! 👍

**Comment by raulk** [comment]
With https://github.com/libp2p/workspace-go-libp2p, this is straightforward to introduce in Go. It'd be worth creating an analogous aggregate repo for js.

**Comment by raulk** [comment]
@vasco-santos incidentally, how do you deal with source control with so many repos? On a one by one basis?

**Comment by vasco-santos** [comment]
The last time we had to do changes in all the repos, we did it manually. Mostly because it was to add the `travis` CI configuration, which could change from repo to repo. Moreover, when we do this type of PRs, we usually leverage this to also update the dependencies of the module, as well as to take other maintenance tasks that we need to do.

All in all, I think we should keep on the radar to create a tool for this, but we have to do it manually for now, it is also fine!

**Comment by yusefnapora** [comment]
awesome, I'll start on this today 👍

**Comment by vasco-santos** [comment]
I am ok with creating the javascript PRs, as it would be good to update dependencies and also update the travis config removing the `commitlint` check [ipfs/aegir#345](https://github.com/ipfs/aegir/issues/345)

**Comment by yusefnapora** [comment]
awesome, thanks @vasco-santos. let me know if you want me to pick any up - I'll focus on go repos for now

**Comment by jacobheun** [comment]
All outstanding JS PRs have been merged. Thanks for going through that gauntlet @vasco-santos ❤️ !

**Comment by vasco-santos** [comment]
And I think that all the JS repos have the badges and dependencies updated, as well as travis CI configured. 

3 PRs are still open, but once they get merged, we can close this issue 🙂

**Comment by jacobheun** [comment]
> 3 PRs are still open

They're all merged 🎉

**Comment by raulk** [comment]
All done here, team! Thanks for the effort @vasco-santos @jacobheun @yusefnapora!
